version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: dss-postgres
    container_name: dss-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
      - PGPASSWORD=postgres12345
      - POSTGRES_DB=dsdojo_db
      - DATABASE_HOST=localhost
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/work/data:/tmp/data

  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: dss-notebook
    container_name: dss-notebook
    ports:
      - "8888:8888"
    environment:
      - PG_PORT=5432
      - PG_USER=padawan
      - PG_PASSWORD=padawan12345
      - PG_DATABASE=dsdojo_db
      - JUPYTER_ENABLE_LAB=yes
    links:
      - db
    volumes:
      - ./docker/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
